export const movies = [
    //Growcast [Episódios]
    {
        img: "https://img.youtube.com/vi/aJ-HZuLcKeA/sddefault.jpg",
        title: "Growcast #00 | Conheça a Growdev",
        link: "https://www.youtube.com/embed/aJ-HZuLcKeA",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/aJ-HZuLcKeA?si=d63jEr5JHBCAAuQa" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/7OWT3lfHYvE/sddefault.jpg",
        title: "Growcast #01 | As profissões do futuro",
        link: "https://www.youtube.com/embed/7OWT3lfHYvE",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/7OWT3lfHYvE?si=0dKl_UwqHEOQL97a" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/ci1eQGPK89o/sddefault.jpg",
        title: "Growcast #02 | Como seguir a carreira internacional?",
        link: "https://www.youtube.com/embed/ci1eQGPK89o",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/ci1eQGPK89o?si=N5qYS5qWGDnkhTQ2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/WM7pGG7OicQ/sddefault.jpg",
        title: "Growcast #03 | Superando os desafios da carreira de Dev!",
        link: "https://www.youtube.com/embed/WM7pGG7OicQ",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/WM7pGG7OicQ?si=f7pA6YiEe-D8USQf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/2c8VOBZ160Y/sddefault.jpg",
        title: "Growcast #04 | Agile Master: tudo sobre a profissão!",
        link: "https://www.youtube.com/embed/2c8VOBZ160Y",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/2c8VOBZ160Y?si=dwWAR5KZyr0K51i7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/mxnEm03cYPc/sddefault.jpg",
        title: "Growcast #5 | Como iniciar na carreira em Desenvolvimento de Softwares?",
        link: "https://www.youtube.com/embed/mxnEm03cYPc",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/mxnEm03cYPc?si=l4TioHQz1AA76Z-u" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/m7DyR07KrOE/sddefault.jpg",
        title: "Growcast #06 | Mulheres e inclusão na tecnologia",
        link: "https://www.youtube.com/embed/m7DyR07KrOE",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/m7DyR07KrOE?si=gYA6ZRCICHHSyzkB" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/vW8G9KPwRL0/sddefault.jpg",
        title: "Growcast #07 | Desenvolvendo profissionais na área de TI",
        link: "https://www.youtube.com/embed/vW8G9KPwRL0",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/vW8G9KPwRL0?si=Qp_mnb2hNXBBjsbW" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/_Ut2KqAqPyk/sddefault.jpg",
        title: "Growcast #8 | A solução que está transformando o mercado de TI no Brasil",
        link: "https://www.youtube.com/embed/_Ut2KqAqPyk",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/_Ut2KqAqPyk?si=XTcchkDMBvPp06PE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/dfDgs0Ive2Q/sddefault.jpg",
        title: "Growcast #9 | Acompanhe com quem realmente entende, tudo sobre o mercado de trabalho no mundo da TI.",
        link: "https://www.youtube.com/embed/dfDgs0Ive2Q",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dfDgs0Ive2Q?si=0z9ZVDOqoUV4dBjv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/ggB0fVqVobs/sddefault.jpg",
        title: "Growcast #10 | Mobile: Um mercado que cresce muito e está transformando vidas.",
        link: "https://www.youtube.com/embed/ggB0fVqVobs",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/ggB0fVqVobs?si=YBbPBCKC2-B8VNQv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/DfVhbfbubAE/sddefault.jpg",
        title: "Growcast #11 | A inteligência por trás dos Dados com Murilo Jovtei - Arezzo & CO",
        link: "https://www.youtube.com/embed/DfVhbfbubAE",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/DfVhbfbubAE?si=LPlfNS3gR_5W6PpA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/VOvngm1kTzg/sddefault.jpg",
        title: "Growcast #12 | Tecnologia Mobile com Laercio Konzen, Desenvolvedor React Native na Arezzo & CO",
        link: "https://www.youtube.com/embed/VOvngm1kTzg",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/VOvngm1kTzg?si=CLg1Zn-8Bg1yKV55" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/5sNcYSupqSU/sddefault.jpg",
        title: "Growcast #13 | Elas no mundo Tech - com Danielle Cosme",
        link: "https://www.youtube.com/embed/5sNcYSupqSU",
        category: "Growcast [Episódios]",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/5sNcYSupqSU?si=0rloquIyiGyygbd_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },

    //Webinar em Flutter
    {
        img: "https://img.youtube.com/vi/WKbLXuP9S-c/sddefault.jpg",
        title: "Webinar - Recriando a interface do Linkedin com Flutter",
        link: "https://www.youtube.com/embed/WKbLXuP9S-c",
        category: "Webinar em Flutter",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/WKbLXuP9S-c?si=xDFIWrQZ3Xj7tmRJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/dJ6y1zMjVXU/sddefault.jpg",
        title: "Webinar - Recriando a interface do Instagram com Flutter",
        link: "https://www.youtube.com/embed/dJ6y1zMjVXU",
        category: "Webinar em Flutter",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dJ6y1zMjVXU?si=sags-rrc2NXpEaSZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/8rdJsqUjsGg/sddefault.jpg",
        title: "Webinar - Recriando a interface do iFood com Flutter",
        link: "https://www.youtube.com/embed/8rdJsqUjsGg",
        category: "Webinar em Flutter",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/8rdJsqUjsGg?si=aGv-XMKLiWa7xSnx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/C4p_7qBsECw/sddefault.jpg",
        title: "Webinar - Recriando a interface do PicPay com Flutter",
        link: "https://www.youtube.com/embed/C4p_7qBsECw",
        category: "Webinar em Flutter",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/C4p_7qBsECw?si=9qyrmB4UYyujlM_z" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/L1pKoMC6hWk/sddefault.jpg",
        title: "Webinar - Recriando o layout do WhatsApp com Flutter",
        link: "https://www.youtube.com/embed/L1pKoMC6hWk",
        category: "Webinar em Flutter",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/L1pKoMC6hWk?si=SG8QTjjTdJ3fkxlr" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },

    //Jornada UX/UI
    {
        img: "https://img.youtube.com/vi/-26aqPtgoEY/sddefault.jpg",
        title: "Live #1 Jornada UX/UI: O papel do UX/UI Designer no desenvolvimento de um produto digital - Growdev",
        link: "https://www.youtube.com/embed/-26aqPtgoEY",
        category: "Jornada UX/UI",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/-26aqPtgoEY?si=oRC0FkaRj9ZZ1vDy" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/8sd3wuKTZMA/sddefault.jpg",
        title: "Live #2 Jornada UX/UI: O profissional de UX/UI Design no mercado digital - Growdev",
        link: "https://www.youtube.com/embed/8sd3wuKTZMA",
        category: "Jornada UX/UI",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/8sd3wuKTZMA?si=kRwXIeNHCWrjRLS2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/ZMZjQ9aRuIY/sddefault.jpg",
        title: "Live #3 Jornada UX/UI: As oportunidades de estudar um programa de formação pagando após formado",
        link: "https://www.youtube.com/embed/ZMZjQ9aRuIY",
        category: "Jornada UX/UI",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/ZMZjQ9aRuIY?si=cVCWJidYWOf98bEx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/cwqDu0ZzbYE/sddefault.jpg",
        title: "Live #4 Jornada UX/UI: Como migrar para o UX/UI Design: a trajetória de uma designer - Growdev",
        link: "https://www.youtube.com/embed/cwqDu0ZzbYE",
        category: "Jornada UX/UI",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/cwqDu0ZzbYE?si=aeMZMo9WjOv385-q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/FiZMowbaiJA/sddefault.jpg",
        title: "Live #5 Jornada UX/UI: O UX/UI Design é para todos?",
        link: "https://www.youtube.com/embed/FiZMowbaiJA",
        category: "Jornada UX/UI",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/FiZMowbaiJA?si=nnqq9llr8avlOzO0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },

    //Diversos
    {
        img: "https://img.youtube.com/vi/QsuhYgsSYQo/sddefault.jpg",
        title: "Célula de talentos - Uma solução Growdev",
        link: "https://www.youtube.com/embed/QsuhYgsSYQo",
        category: "Diversos",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/QsuhYgsSYQo?si=PYEXOxqBlFEjfHf_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/cQDQNX6NXYo/sddefault.jpg",
        title: "Onde trabalhar com qualidade de software? Conheça a Testing Company, empresa parceira da Growdev",
        link: "https://www.youtube.com/embed/cQDQNX6NXYo",
        category: "Diversos",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/cQDQNX6NXYo?si=74jiWOeTgwJoK8Y0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/xHXdbcrfF38/sddefault.jpg",
        title: "Mulheres na Tecnologia: Desafios e sua história de migração de carreira",
        link: "https://www.youtube.com/embed/xHXdbcrfF38",
        category: "Diversos",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/xHXdbcrfF38?si=I8C4hd8VfUeeQIWG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/1LzD5zkgQKo/sddefault.jpg",
        title: "Descomplicando o Front-End: Segredos para Criar Interfaces que Funcionam",
        link: "https://www.youtube.com/embed/1LzD5zkgQKo",
        category: "Diversos",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/1LzD5zkgQKo?si=DzT-DsfXxBISuEZI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
    {
        img: "https://img.youtube.com/vi/DDZlNilnVEI/sddefault.jpg",
        title: "Planeje o Sucesso: Como Traçar e Alcançar Seus Objetivos em 2025",
        link: "https://www.youtube.com/embed/DDZlNilnVEI",
        category: "Diversos",
        highlight: false,
        iframe: '<iframe width="560" height="315" src="https://www.youtube.com/embed/DDZlNilnVEI?si=oZJijuLnBupbe55i" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
    },
];